CREATE TEMP TABLE qd_base AS
SELECT q.user_id AS userid
     , CASE WHEN q.result_cache_hit = 't' THEN 'Result Cache' ELSE 'Default queue' END AS queue
     , date_trunc('hour', q.start_time) AS period
     , q.transaction_id AS xid
     , q.query_id AS query
     , q.queue_time / 1000000.00 AS queue_s
     , q.execution_time / 1000000.00 AS exec_time_s
     , CASE WHEN q.status = 'failed' THEN 1 ELSE 0 END AS aborted
     , q.elapsed_time / 1000000.00 AS total_elapsed_s
FROM sys_query_history q
WHERE q.user_id > 1
  AND q.start_time >= {{START_TIME}}
  AND q.start_time <= {{END_TIME}}
  AND q.query_text LIKE '%replay_start%'
  AND q.status != 'failed';
CREATE TEMP TABLE query_distribution AS (WITH queries AS (SELECT qb.userid, qb.queue, qb.period, qb.xid, qb.query, qb.queue_s, qb.exec_time_s, qb.aborted, qb.total_elapsed_s, uc.user_query_count, DENSE_RANK() OVER (ORDER BY uc.user_query_count) AS rnk FROM qd_base qb INNER JOIN (SELECT userid, count(*) AS user_query_count FROM qd_base GROUP BY userid) uc ON uc.userid = qb.userid), elapsed_time AS (SELECT userid, rnk, queue, aborted, 'Query Latency' AS measure_type, COUNT(*) AS query_count, ROUND(PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY total_elapsed_s),2) AS p25_s, ROUND(PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY total_elapsed_s),2) AS p50_s, ROUND(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY total_elapsed_s),2) AS p75_s, ROUND(PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY total_elapsed_s),2) AS p90_s, ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY total_elapsed_s),2) AS p95_s, ROUND(PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY total_elapsed_s),2) AS p99_s, MAX(total_elapsed_s) AS max_s, AVG(total_elapsed_s) AS avg_s, stddev(total_elapsed_s) AS std_s FROM queries GROUP BY 1,2,3,4,5), exec_time AS (SELECT userid, rnk, queue, aborted, 'Execution Time' AS measure_type, COUNT(*) AS query_count, ROUND(PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY exec_time_s),2) AS p25_s, ROUND(PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY exec_time_s),2) AS p50_s, ROUND(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY exec_time_s),2) AS p75_s, ROUND(PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY exec_time_s),2) AS p90_s, ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY exec_time_s),2) AS p95_s, ROUND(PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY exec_time_s),2) AS p99_s, MAX(exec_time_s) AS max_s, AVG(exec_time_s) AS avg_s, stddev(exec_time_s) AS std_s FROM queries GROUP BY 1,2,3,4,5), queue_time AS (SELECT userid, rnk, queue, aborted, 'Queue Time' AS measure_type, COUNT(*) AS query_count, ROUND(PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY queue_s),2) AS p25_s, ROUND(PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY queue_s),2) AS p50_s, ROUND(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY queue_s),2) AS p75_s, ROUND(PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY queue_s),2) AS p90_s, ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY queue_s),2) AS p95_s, ROUND(PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY queue_s),2) AS p99_s, MAX(queue_s) AS max_s, AVG(queue_s) AS avg_s, stddev(queue_s) AS std_s FROM queries GROUP BY 1,2,3,4,5) SELECT measure_type, userid, rnk, queue, aborted, query_count, p25_s, p50_s, p75_s, p90_s, p95_s, p99_s, max_s, avg_s, std_s FROM exec_time UNION ALL SELECT measure_type, userid, rnk, queue, aborted, query_count, p25_s, p50_s, p75_s, p90_s, p95_s, p99_s, max_s, avg_s, std_s FROM queue_time UNION ALL SELECT measure_type, userid, rnk, queue, aborted, query_count, p25_s, p50_s, p75_s, p90_s, p95_s, p99_s, max_s, avg_s, std_s FROM elapsed_time);

SELECT a.measure_type, CASE WHEN rnk <= 100 THEN u.usename ELSE 'Other Users' END AS usename, a.queue, a.aborted, a.query_count, a.p25_s, a.p50_s, a.p75_s, a.p90_s, a.p95_s, a.p99_s, a.max_s, a.avg_s, a.std_s FROM query_distribution a LEFT JOIN pg_user u ON a.userid = u.usesysid ORDER BY 1, 2, 3, 4
